# Generated by Django 6.0.5 on 2026-06-12 05:16

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_vector_extension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("persona", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                    ),
                ),
                ("status_error", models.TextField(blank=True, default="")),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("embedding_model", models.CharField(default="text-embedding-3-small")),
                ("description_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("embedded_on", models.DateTimeField(blank=True, null=True)),
                ("embedding_started_on", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("seq", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("token_count", models.PositiveIntegerField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.knowledge",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("whatsapp", "Whatsapp"),
                            ("threads", "Threads"),
                        ]
                    ),
                ),
                ("platform_user_id", models.CharField()),
                ("username", models.CharField(blank=True, default="")),
                ("access_token", models.TextField(blank=True, default="")),
                ("token_expires_on", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("expired", "Expired"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="connected",
                    ),
                ),
                ("auto_reply_enabled", models.BooleanField(default=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="core.knowledge",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReplyLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("platform_message_id", models.CharField()),
                ("sender_id", models.CharField()),
                ("sender_name", models.CharField(blank=True, default="")),
                ("inbound_text", models.TextField()),
                ("reply_text", models.TextField(blank=True, default="")),
                ("retrieved_chunks", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="received",
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("sent_message_id", models.CharField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.socialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="knowledge",
            index=models.Index(fields=["created_on"], name="core_knowle_created_09e284_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(fields=["created_on"], name="core_knowle_created_9b73cf_idx"),
        ),
        migrations.AddConstraint(
            model_name="knowledgechunk",
            constraint=models.UniqueConstraint(
                fields=("knowledge", "seq"), name="uniq_kchunk_knowledge_seq"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(fields=["created_on"], name="core_social_created_b3403a_idx"),
        ),
        migrations.AddConstraint(
            model_name="socialaccount",
            constraint=models.UniqueConstraint(
                fields=("platform", "platform_user_id"), name="uniq_account_platform_uid"
            ),
        ),
        migrations.AddIndex(
            model_name="replylog",
            index=models.Index(fields=["created_on"], name="core_replyl_created_37308e_idx"),
        ),
        migrations.AddConstraint(
            model_name="replylog",
            constraint=models.UniqueConstraint(
                fields=("account", "platform_message_id"), name="uniq_replylog_account_msg"
            ),
        ),
    ]
